### ISSUE TITLE
Lafayette channel freezes xbmc

### ISSUE THREAD

**Issue by jposse** [stieg/xbmc_npr#1]
Can anyone else confirm this issue? I'm running via Crystalbuntu / Apple TV1 config. Other NPR stations seem to work, but when choosing the NPR station from Lafayette, Louisiana it freezes the whole XBMC interface. 

Thanks.
JP

**Comment by stieg** [comment]
Hey jposse,
   I just tried to stream that station and it appears to work well for me.  You are referring to the KRVS-FM stream yes?  Perhaps their site was having a streaming issue at the time.  Are you still seeing this issue?

**Comment by jposse** [comment]
Hi Stieg.

It turns out that this was most likely a problem on my end. I had other problems that led to intermittent audio issues (it turned out that lots of other NPR stations caused the lockup as well). 

For others that may be searching: You can't assume that Crystalbuntu actually set the right audio settings for your Apple TV. Here are the things I changed, which now everything is working fine. 
1. Changed the audio output to HDMI to "custom plughw:0,3" 
2. Changed passthrough device to "custom plughw:0,3"
3. Disabled OpenGL meters during audio playback. 

Thanks for your help, but turns out it my issue.
